# Generated by Django 2.2.4 on 2019-09-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
