# Generated by Django 2.2.4 on 2019-10-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20191002_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd',
            name='reviews',
        ),
        migrations.AddField(
            model_name='bd',
            name='reviews',
            field=models.ManyToManyField(null=True, to='work.Review', verbose_name='Отзывы о товаре'),
        ),
    ]
