# Generated by Django 2.2.4 on 2019-10-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20191002_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='bd',
            field=models.ManyToManyField(to='work.Bd', verbose_name='Отзывы о товаре'),
        ),
    ]
