# Generated by Django 2.2.4 on 2019-10-02 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20191002_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='bd',
        ),
        migrations.AddField(
            model_name='review',
            name='bd',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Bd', verbose_name='Отзывы о товаре'),
            preserve_default=False,
        ),
    ]
