# Generated by Django 2.2.4 on 2019-10-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bd',
            options={'ordering': ['-description'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'КатегорииКатегория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='bd',
            name='title',
            field=models.CharField(max_length=50, verbose_name='название товара'),
        ),
        migrations.AlterField(
            model_name='bd',
            name='сategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='work.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_number',
            field=models.IntegerField(default=1, verbose_name='Количество категорий товара'),
        ),
    ]
