# Generated by Django 2.2.4 on 2019-10-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_оrder'),
    ]

    operations = [
        migrations.AddField(
            model_name='оrder',
            name='total_number',
            field=models.FloatField(default=0, verbose_name='Общая сумма'),
        ),
    ]
