# Generated by Django 2.2.4 on 2019-10-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_auto_20191004_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd',
            old_name='сategory',
            new_name='category',
        ),
    ]
