# Generated by Django 2.2.4 on 2019-09-08 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Статья', max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(default='', upload_to=None, verbose_name='Тематическое изображение статьи')),
                ('content', models.TextField(default='', verbose_name='Текст статья')),
                ('paid', models.BooleanField(default=False, verbose_name='Платную подписка')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pay', models.BooleanField(default=False, verbose_name='Оплатил контент?')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
